using FinanceManagement.Application.JournalMaster.JournalThresholdRule.Commands.CreateJournalThresholdRule;
using FinanceManagement.Application.JournalMaster.JournalThresholdRule.Commands.DeleteJournalThresholdRule;
using FinanceManagement.Application.JournalMaster.JournalThresholdRule.Commands.UpdateJournalThresholdRule;
using FinanceManagement.Application.JournalMaster.JournalThresholdRule.Queries.GetAllJournalFlag;
using FinanceManagement.Application.JournalMaster.JournalThresholdRule.Queries.GetAllJournalThresholdRule;
using FinanceManagement.Application.JournalMaster.JournalThresholdRule.Queries.GetJournalThresholdRuleAutoComplete;
using FinanceManagement.Application.JournalMaster.JournalThresholdRule.Queries.GetJournalThresholdRuleById;
using MediatR;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FinanceManagement.Presentation.Controllers.JournalMaster
{
    [Route("api/finance/[controller]")]
    public class JournalThresholdRuleController : FinanceManagement.Presentation.Controllers.ApiControllerBase
    {
        public JournalThresholdRuleController(IMediator mediator) : base(mediator) { }

        [HttpGet]
        public async Task<IActionResult> GetAllAsync(
            [FromQuery] int PageNumber,
            [FromQuery] int PageSize,
            [FromQuery] string? SearchTerm = null)
        {
            var result = await Mediator.Send(new GetAllJournalThresholdRuleQuery
            {
                PageNumber = PageNumber,
                PageSize = PageSize,
                SearchTerm = SearchTerm
            });

            return Ok(new
            {
                StatusCode = StatusCodes.Status200OK,
                data = result.Data,
                TotalCount = result.TotalCount,
                PageNumber = result.PageNumber,
                PageSize = result.PageSize
            });
        }

        [HttpGet("by-name")]
        public async Task<IActionResult> GetAutoCompleteAsync([FromQuery] string? term = null)
        {
            var result = await Mediator.Send(new GetJournalThresholdRuleAutoCompleteQuery(term ?? string.Empty));
            return Ok(new { StatusCode = StatusCodes.Status200OK, data = result });
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetByIdAsync(int id)
        {
            var result = await Mediator.Send(new GetJournalThresholdRuleByIdQuery { Id = id });
            return Ok(new { StatusCode = StatusCodes.Status200OK, data = result });
        }

        // US-GL01-16B — read flagged journals (flags are auto-generated by the flagging engine).
        [HttpGet("flags")]
        public async Task<IActionResult> GetFlagsAsync(
            [FromQuery] int PageNumber,
            [FromQuery] int PageSize,
            [FromQuery] int? JournalHeaderId = null)
        {
            var result = await Mediator.Send(new GetAllJournalFlagQuery
            {
                PageNumber = PageNumber,
                PageSize = PageSize,
                JournalHeaderId = JournalHeaderId
            });

            return Ok(new
            {
                StatusCode = StatusCodes.Status200OK,
                data = result.Data,
                TotalCount = result.TotalCount,
                PageNumber = result.PageNumber,
                PageSize = result.PageSize
            });
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] CreateJournalThresholdRuleCommand command)
        {
            var result = await Mediator.Send(command);
            return Ok(new { StatusCode = StatusCodes.Status200OK, isSuccess = result.IsSuccess, message = result.Message, data = result.Data });
        }

        [HttpPut]
        public async Task<IActionResult> Update([FromBody] UpdateJournalThresholdRuleCommand command)
        {
            var result = await Mediator.Send(command);
            return Ok(new { StatusCode = StatusCodes.Status200OK, isSuccess = result.IsSuccess, message = result.Message, data = result.Data });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await Mediator.Send(new DeleteJournalThresholdRuleCommand(id));
            return Ok(new
            {
                StatusCode = StatusCodes.Status200OK,
                isSuccess = result,
                message = result ? "Journal threshold rule deleted successfully." : "Failed to delete journal threshold rule."
            });
        }
    }
}
