// <auto-generated />
using System;
using InventoryManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218095617_itemmasteronspot")]
    partial class itemmasteronspot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Entities.Budget.BudgetDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BudgetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BudgetId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.ToTable("BudgetDetail", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Budget.BudgetLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("BudgetDetailId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("NewBudgetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldBudgetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("BudgetDetailId");

                    b.ToTable("BudgetLog", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Budget.BudgetMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetGroupId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<bool?>("Is_MRApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("Is_MRApplicable");

                    b.Property<bool?>("Is_POApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("Is_POApplicable");

                    b.Property<bool?>("Is_ServiceApplicable")
                        .HasColumnType("bit")
                        .HasColumnName("Is_ServiceApplicable");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("YearBudgetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("BudgetMaster", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.HSNMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CGSTPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("CGSTPercentage");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Description");

                    b.Property<int>("GSTCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("GSTCategoryId");

                    b.Property<decimal>("GSTPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("GSTPercentage");

                    b.Property<string>("HSNCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("HSNCode");

                    b.Property<decimal>("IGSTPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("IGSTPercentage");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("SGSTPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("SGSTPercentage");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeId");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ValidFrom");

                    b.HasKey("Id");

                    b.HasIndex("GSTCategoryId");

                    b.HasIndex("HSNCode")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.ToTable("HSNMaster", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("DeptId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsBudgetApplicable")
                        .HasColumnType("Bit")
                        .HasColumnName("IsBudgetApplicable");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsGroup")
                        .HasColumnType("bit")
                        .HasColumnName("IsGroup");

                    b.Property<string>("ItemCategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ItemCategoryName");

                    b.Property<int>("ItemGroupId")
                        .HasColumnType("int")
                        .HasColumnName("ItemGroupId");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("ParentCategoryId");

                    b.Property<int?>("RootCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("RootCategoryId");

                    b.HasKey("Id");

                    b.HasIndex("ItemGroupId");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("RootCategoryId");

                    b.ToTable("ItemCategory", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowNegativeStock")
                        .HasColumnType("bit")
                        .HasColumnName("AllowNegativeStock");

                    b.Property<bool>("ApplyBatchNumber")
                        .HasColumnType("bit")
                        .HasColumnName("ApplyBatchNumber");

                    b.Property<bool>("BatchManagement")
                        .HasColumnType("bit")
                        .HasColumnName("BatchManagement");

                    b.Property<string>("BatchNumberSeries")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("BatchNumberSeries");

                    b.Property<int?>("DefaultMaterialRequestTypeId")
                        .HasColumnType("int")
                        .HasColumnName("DefaultMaterialRequestTypeId");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemId");

                    b.Property<decimal?>("LowerTolerance")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("LowerTolerance");

                    b.Property<int?>("ReorderLevel")
                        .HasColumnType("int")
                        .HasColumnName("ReorderLevel");

                    b.Property<int?>("ReorderQty")
                        .HasColumnType("int")
                        .HasColumnName("ReorderQty");

                    b.Property<int?>("RequestTypeId")
                        .HasColumnType("int")
                        .HasColumnName("RequestTypeId");

                    b.Property<string>("SerialNumberSeries")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SerialNumberSeries");

                    b.Property<int?>("ShelfLife")
                        .HasColumnType("int")
                        .HasColumnName("ShelfLife");

                    b.Property<decimal?>("UpperTolerance")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("UpperTolerance");

                    b.Property<int?>("ValuationMethodId")
                        .HasColumnType("int")
                        .HasColumnName("ValuationMethodId");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("Weight");

                    b.Property<int?>("WeightUomId")
                        .HasColumnType("int")
                        .HasColumnName("WeightUomId");

                    b.HasKey("Id");

                    b.HasIndex("DefaultMaterialRequestTypeId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("ValuationMethodId");

                    b.HasIndex("WeightUomId");

                    b.ToTable("ItemInventory", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("Update")
                        .HasColumnName("Action");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("CorrelationId");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(64)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(45)")
                        .HasColumnName("CreatedIP");

                    b.Property<int>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("EntityName");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NewValue");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OldValue");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PropertyName");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_ItemLogs_CorrelationId");

                    b.HasIndex("EntityName", "EntityId", "CreatedDate")
                        .HasDatabaseName("IX_ItemLogs_Entity_ThenDate");

                    b.ToTable("ItemLogs", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemManufacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemId");

                    b.Property<int>("ManufacturingTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ManufacturingTypeId");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ManufacturingTypeId");

                    b.ToTable("ItemManufacture", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<int?>("HSNId")
                        .HasColumnType("int")
                        .HasColumnName("HSNId");

                    b.Property<bool>("HasVariants")
                        .HasColumnType("bit")
                        .HasColumnName("HasVariants");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsCapitalItem")
                        .HasColumnType("bit")
                        .HasColumnName("IsCapitalItem");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsOnSpot")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStockItem")
                        .HasColumnType("bit")
                        .HasColumnName("IsStockItem");

                    b.Property<int?>("IssueRuleId")
                        .HasColumnType("int")
                        .HasColumnName("IssueRuleId");

                    b.Property<int?>("ItemCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("ItemCategoryId");

                    b.Property<int?>("ItemClassificationId")
                        .HasColumnType("int")
                        .HasColumnName("ItemClassificationId");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ItemCode");

                    b.Property<int?>("ItemGroupId")
                        .HasColumnType("int")
                        .HasColumnName("ItemGroupId");

                    b.Property<string>("ItemImage")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ItemImage");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ItemName");

                    b.Property<bool>("MaintainStock")
                        .HasColumnType("bit")
                        .HasColumnName("MaintainStock");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.Property<int?>("ParentItemId")
                        .HasColumnType("int")
                        .HasColumnName("ParentItemId");

                    b.Property<int?>("StockUomId")
                        .HasColumnType("int")
                        .HasColumnName("StockUomId");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("ValidFrom");

                    b.Property<int?>("XPlantMaterialStatusId")
                        .HasColumnType("int")
                        .HasColumnName("XPlantMaterialStatusId");

                    b.HasKey("Id");

                    b.HasIndex("HSNId");

                    b.HasIndex("IssueRuleId");

                    b.HasIndex("ItemCategoryId");

                    b.HasIndex("ItemClassificationId");

                    b.HasIndex("ItemGroupId");

                    b.HasIndex("ParentItemId");

                    b.HasIndex("StockUomId");

                    b.HasIndex("XPlantMaterialStatusId");

                    b.ToTable("ItemMaster", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutomaticPo")
                        .HasColumnType("bit")
                        .HasColumnName("AutomaticPo");

                    b.Property<int?>("GrProcessingTimeDays")
                        .HasColumnType("int")
                        .HasColumnName("GrProcessingTimeDays");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemId");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("int")
                        .HasColumnName("LeadTimeDays");

                    b.Property<int?>("OriginCountryId")
                        .HasColumnType("int")
                        .HasColumnName("OriginCountryId");

                    b.Property<decimal?>("PurchaseRate")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("PurchaseRate");

                    b.Property<int?>("PurchaseUomId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseUomId");

                    b.Property<int?>("SafetyStock")
                        .HasColumnType("int")
                        .HasColumnName("SafetyStock");

                    b.Property<int?>("SourceOfItem")
                        .HasColumnType("int")
                        .HasColumnName("SourceOfItem");

                    b.Property<string>("TariffNumber")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TariffNumber");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.HasIndex("PurchaseUomId");

                    b.HasIndex("SourceOfItem");

                    b.ToTable("ItemPurchase", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemQuality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CertificateTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CertificateTypeId");

                    b.Property<int?>("InspLotProcessingTime")
                        .HasColumnType("int")
                        .HasColumnName("InspLotProcessingTime");

                    b.Property<bool>("InspectionRequired")
                        .HasColumnType("bit")
                        .HasColumnName("InspectionRequired");

                    b.Property<int?>("InspectionTemplateId")
                        .HasColumnType("int")
                        .HasColumnName("InspectionTemplateId");

                    b.Property<bool>("IsCertificateRequiredFromSupplier")
                        .HasColumnType("bit")
                        .HasColumnName("IsCertificateRequiredFromSupplier");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemId");

                    b.Property<bool>("QualityInspectionFree")
                        .HasColumnType("bit")
                        .HasColumnName("QualityInspectionFree");

                    b.HasKey("Id");

                    b.HasIndex("CertificateTypeId");

                    b.HasIndex("InspectionTemplateId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("ItemQuality", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("DefaultSupplier")
                        .HasColumnType("bit")
                        .HasColumnName("DefaultSupplier");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemId");

                    b.Property<int?>("LeadTime")
                        .HasColumnType("int")
                        .HasColumnName("LeadTime");

                    b.Property<int?>("MOQ")
                        .HasColumnType("int")
                        .HasColumnName("MOQ");

                    b.Property<int?>("MOQUomId")
                        .HasColumnType("int")
                        .HasColumnName("MOQUomId");

                    b.Property<int?>("PackageUomId")
                        .HasColumnType("int")
                        .HasColumnName("PackageUomId");

                    b.Property<decimal?>("PackageValue")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("PackageValue");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierId");

                    b.Property<string>("SupplierPartNo")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SupplierPartNo");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemSupplier", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemUOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ConversionRate")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("ConversionRate");

                    b.Property<int>("ConversionUOMId")
                        .HasColumnType("int")
                        .HasColumnName("ConversionUOMId");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemId");

                    b.HasKey("Id");

                    b.HasIndex("ConversionUOMId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemUOM", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.Templates.InspectionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateName");

                    b.ToTable("InspectionTemplate", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.Variant.ItemVariantAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttributeGroupId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("VariantBasedOn")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttributeGroupId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("VariantBasedOn");

                    b.HasIndex("ItemId", "AttributeId")
                        .IsUnique();

                    b.HasIndex("ItemId", "Order")
                        .IsUnique();

                    b.ToTable("ItemVariantAttribute", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.Variant.ItemVariantValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ParentItemId")
                        .HasColumnType("int");

                    b.Property<int>("VariantAttributeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentItemId");

                    b.HasIndex("VariantAttributeId");

                    b.HasIndex("ItemId", "VariantAttributeId")
                        .IsUnique()
                        .HasDatabaseName("UX_ItemVariantValue_Item_VarAttr");

                    b.HasIndex("ItemId", "VariantAttributeId", "OptionValue")
                        .IsUnique();

                    b.ToTable("ItemVariantValue", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemGroupCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ItemGroupCode");

                    b.Property<string>("ItemGroupName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ItemGroupName");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id");

                    b.ToTable("ItemGroup", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.PutAway.PutAwayRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ItemCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ItemGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemCategoryId");

                    b.HasIndex("ItemGroupId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UnitId", "WarehouseId", "ItemGroupId", "ItemCategoryId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("UX_PutAwayRule_Scope")
                        .HasFilter("[ItemId] IS NOT NULL");

                    b.ToTable("PutAwayRule", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.PutAway.PutAwayStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<int>("PutAwayRuleId")
                        .HasColumnType("int");

                    b.Property<int>("StorageTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StorageTypeId");

                    b.HasIndex("PutAwayRuleId", "PriorityId")
                        .IsUnique()
                        .HasDatabaseName("UX_PutAwayStrategy_PriorityPerRule")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("PutAwayStrategy", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.MiscMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Code");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MiscTypeId")
                        .HasColumnType("int")
                        .HasColumnName("MiscTypeId");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sortOrder");

                    b.HasKey("Id");

                    b.HasIndex("MiscTypeId");

                    b.ToTable("MiscMaster", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.MiscTypeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("MiscTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MiscTypeCode");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("MiscTypeMaster", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.UOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SortOrder");

                    b.Property<string>("UOMName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UOMName");

                    b.Property<int>("UOMTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UOMTypeId");

                    b.ToTable("UOM", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.UOMConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConversionValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FromUOMId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ToUOMId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromUOMId");

                    b.HasIndex("ToUOMId");

                    b.ToTable("UOMConversion", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.item.ItemDetail.Templates.InspectionParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcceptanceCriteriaValue")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaximumValue")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("MinimumValue")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Numeric")
                        .HasColumnType("bit");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("InspectionParameter", "Inventory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Budget.BudgetDetail", b =>
                {
                    b.HasOne("Core.Domain.Entities.Budget.BudgetMaster", "BudgetMaster")
                        .WithMany("BudgetDetail")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetMaster");
                });

            modelBuilder.Entity("Core.Domain.Entities.Budget.BudgetLog", b =>
                {
                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscAction")
                        .WithMany("BudgetAction")
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Budget.BudgetDetail", "BudgetDetail")
                        .WithMany("BudgetLog")
                        .HasForeignKey("BudgetDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetDetail");

                    b.Navigation("MiscAction");
                });

            modelBuilder.Entity("Core.Domain.Entities.HSNMaster", b =>
                {
                    b.HasOne("Core.Domain.Entities.MiscMaster", "GstCategory")
                        .WithMany("HSNMasters")
                        .HasForeignKey("GSTCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.MiscMaster", "Type")
                        .WithMany("TypeHSNs")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HSNMaster_MiscMaster_Type");

                    b.Navigation("GstCategory");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemCategory", b =>
                {
                    b.HasOne("Core.Domain.Entities.Item.ItemGroup", "ItemGroup")
                        .WithMany("ItemCategory")
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Item.ItemCategory", "ItemCategoryParent")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.Item.ItemCategory", "RootCategory")
                        .WithMany()
                        .HasForeignKey("RootCategoryId");

                    b.Navigation("ItemCategoryParent");

                    b.Navigation("ItemGroup");

                    b.Navigation("RootCategory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemInventory", b =>
                {
                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscDefaultMaterialRequestType")
                        .WithMany("ItemInventoryDefaultMaterialRequestType")
                        .HasForeignKey("DefaultMaterialRequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.ItemMaster", "Item")
                        .WithOne("Inventory")
                        .HasForeignKey("Core.Domain.Entities.Item.ItemDetail.ItemInventory", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscRequestType")
                        .WithMany("ItemInventoryRequestType")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscValuationMethod")
                        .WithMany("ItemInventoryValuationMethod")
                        .HasForeignKey("ValuationMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.UOM", "WeightUOM")
                        .WithMany("InventoryUOM")
                        .HasForeignKey("WeightUomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Item");

                    b.Navigation("MiscDefaultMaterialRequestType");

                    b.Navigation("MiscRequestType");

                    b.Navigation("MiscValuationMethod");

                    b.Navigation("WeightUOM");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemManufacture", b =>
                {
                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.ItemMaster", "Item")
                        .WithMany("Manufacture")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscManufactureType")
                        .WithMany("ItemManufactureType")
                        .HasForeignKey("ManufacturingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("MiscManufactureType");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemMaster", b =>
                {
                    b.HasOne("Core.Domain.Entities.HSNMaster", "HSNMaster")
                        .WithMany("ItemMasterHSN")
                        .HasForeignKey("HSNId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscIssueRule")
                        .WithMany("ItemMasterIssueRule")
                        .HasForeignKey("IssueRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.Item.ItemCategory", "ItemCategory")
                        .WithMany("ItemMasterCategory")
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscClassification")
                        .WithMany("ItemMasterClassification")
                        .HasForeignKey("ItemClassificationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.Item.ItemGroup", "ItemGroup")
                        .WithMany("ItemMasterGroup")
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.ItemMaster", "ParentItem")
                        .WithMany("ChildItems")
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.UOM", "UOM")
                        .WithMany("ItemMasterUOM")
                        .HasForeignKey("StockUomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscStatus")
                        .WithMany("ItemMasterStatus")
                        .HasForeignKey("XPlantMaterialStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HSNMaster");

                    b.Navigation("ItemCategory");

                    b.Navigation("ItemGroup");

                    b.Navigation("MiscClassification");

                    b.Navigation("MiscIssueRule");

                    b.Navigation("MiscStatus");

                    b.Navigation("ParentItem");

                    b.Navigation("UOM");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemPurchase", b =>
                {
                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.ItemMaster", "Item")
                        .WithOne("Purchase")
                        .HasForeignKey("Core.Domain.Entities.Item.ItemDetail.ItemPurchase", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.UOM", "PurchaseUOM")
                        .WithMany("PurchaseUOM")
                        .HasForeignKey("PurchaseUomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscSource")
                        .WithMany("ItemPurchaseSource")
                        .HasForeignKey("SourceOfItem")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Item");

                    b.Navigation("MiscSource");

                    b.Navigation("PurchaseUOM");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemQuality", b =>
                {
                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscCertificateType")
                        .WithMany("ItemQualityCertificateType")
                        .HasForeignKey("CertificateTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.Templates.InspectionTemplate", "InspectionTemplate")
                        .WithMany("Items")
                        .HasForeignKey("InspectionTemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.ItemMaster", "Item")
                        .WithOne("Quality")
                        .HasForeignKey("Core.Domain.Entities.Item.ItemDetail.ItemQuality", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InspectionTemplate");

                    b.Navigation("Item");

                    b.Navigation("MiscCertificateType");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemSupplier", b =>
                {
                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.ItemMaster", "Item")
                        .WithMany("Suppliers")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemUOM", b =>
                {
                    b.HasOne("Core.Domain.Entities.UOM", "ConversionUOM")
                        .WithMany("ItemUOM")
                        .HasForeignKey("ConversionUOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.ItemMaster", "Item")
                        .WithMany("ItemUOMs")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConversionUOM");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.Variant.ItemVariantAttribute", b =>
                {
                    b.HasOne("Core.Domain.Entities.MiscTypeMaster", "MiscAttributeGroup")
                        .WithMany("ItemVariantAttributeGroup")
                        .HasForeignKey("AttributeGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscAttribute")
                        .WithMany("ItemAttribute")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.ItemMaster", "ItemMaster")
                        .WithMany("VariantAttributes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscVariantBasedOn")
                        .WithMany("ItemAttributeBasedOn")
                        .HasForeignKey("VariantBasedOn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemMaster");

                    b.Navigation("MiscAttribute");

                    b.Navigation("MiscAttributeGroup");

                    b.Navigation("MiscVariantBasedOn");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.Variant.ItemVariantValue", b =>
                {
                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.ItemMaster", "ItemMaster")
                        .WithMany("VariantValues")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.ItemMaster", "ParentItem")
                        .WithMany("VariantParentItem")
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.Variant.ItemVariantAttribute", "VariantAttribute")
                        .WithMany("ItemVariantValues")
                        .HasForeignKey("VariantAttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemMaster");

                    b.Navigation("ParentItem");

                    b.Navigation("VariantAttribute");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.PutAway.PutAwayRule", b =>
                {
                    b.HasOne("Core.Domain.Entities.Item.ItemCategory", "ItemCategory")
                        .WithMany("PutAwayRuleCategory")
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Item.ItemGroup", "ItemGroup")
                        .WithMany("PutAwayRuleGroup")
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.ItemMaster", "ItemMaster")
                        .WithMany("PutAwayRules")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ItemCategory");

                    b.Navigation("ItemGroup");

                    b.Navigation("ItemMaster");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.PutAway.PutAwayStrategy", b =>
                {
                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscPriority")
                        .WithMany("PutAwayStrategyPriority")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.Item.PutAway.PutAwayRule", "PutAwayRule")
                        .WithMany("Strategies")
                        .HasForeignKey("PutAwayRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.MiscMaster", "MiscStorageTypeId")
                        .WithMany("PutAwayStrategyStorageType")
                        .HasForeignKey("StorageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MiscPriority");

                    b.Navigation("MiscStorageTypeId");

                    b.Navigation("PutAwayRule");
                });

            modelBuilder.Entity("Core.Domain.Entities.MiscMaster", b =>
                {
                    b.HasOne("Core.Domain.Entities.MiscTypeMaster", "MiscTypeMaster")
                        .WithMany("MiscMaster")
                        .HasForeignKey("MiscTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MiscTypeMaster");
                });

            modelBuilder.Entity("Core.Domain.Entities.UOM", b =>
                {
                    b.HasOne("Core.Domain.Entities.MiscMaster", "UOMType")
                        .WithMany("UOMs")
                        .HasForeignKey("UOMTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UOMType");
                });

            modelBuilder.Entity("Core.Domain.Entities.UOMConversion", b =>
                {
                    b.HasOne("Core.Domain.Entities.UOM", "FromUOM")
                        .WithMany("FromUOMConversions")
                        .HasForeignKey("FromUOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Domain.Entities.UOM", "ToUOM")
                        .WithMany("ToUOMConversions")
                        .HasForeignKey("ToUOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUOM");

                    b.Navigation("ToUOM");
                });

            modelBuilder.Entity("Core.Domain.Entities.item.ItemDetail.Templates.InspectionParameter", b =>
                {
                    b.HasOne("Core.Domain.Entities.Item.ItemDetail.Templates.InspectionTemplate", "Template")
                        .WithMany("Parameters")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Core.Domain.Entities.Budget.BudgetDetail", b =>
                {
                    b.Navigation("BudgetLog");
                });

            modelBuilder.Entity("Core.Domain.Entities.Budget.BudgetMaster", b =>
                {
                    b.Navigation("BudgetDetail");
                });

            modelBuilder.Entity("Core.Domain.Entities.HSNMaster", b =>
                {
                    b.Navigation("ItemMasterHSN");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemCategory", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("ItemMasterCategory");

                    b.Navigation("PutAwayRuleCategory");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.ItemMaster", b =>
                {
                    b.Navigation("ChildItems");

                    b.Navigation("Inventory");

                    b.Navigation("ItemUOMs");

                    b.Navigation("Manufacture");

                    b.Navigation("Purchase");

                    b.Navigation("PutAwayRules");

                    b.Navigation("Quality");

                    b.Navigation("Suppliers");

                    b.Navigation("VariantAttributes");

                    b.Navigation("VariantParentItem");

                    b.Navigation("VariantValues");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.Templates.InspectionTemplate", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemDetail.Variant.ItemVariantAttribute", b =>
                {
                    b.Navigation("ItemVariantValues");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.ItemGroup", b =>
                {
                    b.Navigation("ItemCategory");

                    b.Navigation("ItemMasterGroup");

                    b.Navigation("PutAwayRuleGroup");
                });

            modelBuilder.Entity("Core.Domain.Entities.Item.PutAway.PutAwayRule", b =>
                {
                    b.Navigation("Strategies");
                });

            modelBuilder.Entity("Core.Domain.Entities.MiscMaster", b =>
                {
                    b.Navigation("BudgetAction");

                    b.Navigation("HSNMasters");

                    b.Navigation("ItemAttribute");

                    b.Navigation("ItemAttributeBasedOn");

                    b.Navigation("ItemInventoryDefaultMaterialRequestType");

                    b.Navigation("ItemInventoryRequestType");

                    b.Navigation("ItemInventoryValuationMethod");

                    b.Navigation("ItemManufactureType");

                    b.Navigation("ItemMasterClassification");

                    b.Navigation("ItemMasterIssueRule");

                    b.Navigation("ItemMasterStatus");

                    b.Navigation("ItemPurchaseSource");

                    b.Navigation("ItemQualityCertificateType");

                    b.Navigation("PutAwayStrategyPriority");

                    b.Navigation("PutAwayStrategyStorageType");

                    b.Navigation("TypeHSNs");

                    b.Navigation("UOMs");
                });

            modelBuilder.Entity("Core.Domain.Entities.MiscTypeMaster", b =>
                {
                    b.Navigation("ItemVariantAttributeGroup");

                    b.Navigation("MiscMaster");
                });

            modelBuilder.Entity("Core.Domain.Entities.UOM", b =>
                {
                    b.Navigation("FromUOMConversions");

                    b.Navigation("InventoryUOM");

                    b.Navigation("ItemMasterUOM");

                    b.Navigation("ItemUOM");

                    b.Navigation("PurchaseUOM");

                    b.Navigation("ToUOMConversions");
                });
#pragma warning restore 612, 618
        }
    }
}
