// <auto-generated />
using System;
using BudgetManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable
#pragma warning disable CS8981

namespace BudgetManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251204070300_budgetmonth")]
    partial class budgetmonth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetManagement.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Scope")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ScopeKey")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "EntityId", "CreatedDate")
                        .HasDatabaseName("IX_ActivityLog_Entity_CreatedDate");

                    b.ToTable("ActivityLog", "Budget");
                });

            modelBuilder.Entity("BudgetManagement.Domain.Entities.BudgetAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllocationTypeId")
                        .HasColumnType("int")
                        .HasColumnName("AllocationTypeId");

                    b.Property<decimal>("ApprovedAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ApprovedAmount");

                    b.Property<int>("BudgetGroupId")
                        .HasColumnType("int")
                        .HasColumnName("BudgetGroupId");

                    b.Property<int?>("BudgetSubGroupId")
                        .HasColumnType("int")
                        .HasColumnName("BudgetSubGroupId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("FinancialYearId")
                        .HasColumnType("int")
                        .HasColumnName("FinancialYearId");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("RatePerSpindle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("RatePerSpindle");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Remarks");

                    b.Property<int>("RequestById")
                        .HasColumnType("int")
                        .HasColumnName("RequestById");

                    b.Property<int>("RequestMonthId")
                        .HasColumnType("int")
                        .HasColumnName("RequestMonthId");

                    b.Property<int?>("RequestTypeId")
                        .HasColumnType("int")
                        .HasColumnName("RequestTypeId");

                    b.Property<int?>("SpindleCount")
                        .HasColumnType("int")
                        .HasColumnName("SpindleCount");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id");

                    b.HasIndex("AllocationTypeId");

                    b.HasIndex("BudgetGroupId");

                    b.HasIndex("RequestById");

                    b.HasIndex("RequestMonthId");

                    b.HasIndex("RequestTypeId");

                    b.ToTable("BudgetAllocation", "Budget");
                });

            modelBuilder.Entity("BudgetManagement.Domain.Entities.BudgetGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AllocatedPercentage")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AllocatedPercentage");

                    b.Property<decimal?>("AllocatedSpindleCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AllocatedSpindleCost");

                    b.Property<int?>("AllocationRuleId")
                        .HasColumnType("int")
                        .HasColumnName("AllocationRuleId");

                    b.Property<int>("CostCenterId")
                        .HasColumnType("int")
                        .HasColumnName("CostCenterId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyId");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentId");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsParent")
                        .HasColumnType("bit")
                        .HasColumnName("IsParent");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<int?>("ParentBudgetGroupId")
                        .HasColumnType("int")
                        .HasColumnName("ParentBudgetGroupId");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id");

                    b.HasIndex("AllocationRuleId");

                    b.HasIndex("ParentBudgetGroupId");

                    b.HasIndex("UnitId", "DepartmentId", "Name")
                        .IsUnique();

                    b.ToTable("BudgetGroup", "Budget");
                });

            modelBuilder.Entity("BudgetManagement.Domain.Entities.BudgetRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("BudgetSbuGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CostCenterId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("FinYearId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<decimal?>("LastMonthUtilized")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RemainingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("RequestAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RequestById")
                        .HasColumnType("int");

                    b.Property<string>("RequestCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RequestMonthId")
                        .HasColumnType("int");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestById");

                    b.HasIndex("RequestMonthId");

                    b.HasIndex("RequestTypeId");

                    b.ToTable("BudgetRequest", "Budget");
                });

            modelBuilder.Entity("BudgetManagement.Domain.Entities.MiscMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Code");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MiscTypeId")
                        .HasColumnType("int")
                        .HasColumnName("MiscTypeId");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sortOrder");

                    b.HasKey("Id");

                    b.HasIndex("MiscTypeId");

                    b.ToTable("MiscMaster", "Budget");
                });

            modelBuilder.Entity("BudgetManagement.Domain.Entities.MiscTypeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("MiscTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MiscTypeCode");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("MiscTypeMaster", "Budget");
                });

            modelBuilder.Entity("BudgetManagement.Domain.Entities.BudgetAllocation", b =>
                {
                    b.HasOne("BudgetManagement.Domain.Entities.MiscMaster", "AllocationRuleType")
                        .WithMany("BudgetAllocationType")
                        .HasForeignKey("AllocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetManagement.Domain.Entities.BudgetGroup", "BudgetGroupType")
                        .WithMany("BudgetAllocationGroupType")
                        .HasForeignKey("BudgetGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetManagement.Domain.Entities.MiscMaster", "RequestMonthYearType")
                        .WithMany("BudgetRequestByType")
                        .HasForeignKey("RequestById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetManagement.Domain.Entities.MiscMaster", "RequestMonthType")
                        .WithMany("BudgetRequestMonthType")
                        .HasForeignKey("RequestMonthId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetManagement.Domain.Entities.BudgetRequest", "BudgetRequestType")
                        .WithMany("BudgetAllocationRequestType")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AllocationRuleType");

                    b.Navigation("BudgetGroupType");

                    b.Navigation("BudgetRequestType");

                    b.Navigation("RequestMonthType");

                    b.Navigation("RequestMonthYearType");
                });

            modelBuilder.Entity("BudgetManagement.Domain.Entities.BudgetGroup", b =>
                {
                    b.HasOne("BudgetManagement.Domain.Entities.MiscMaster", "AllocationRule")
                        .WithMany("BudgetAllocationRules")
                        .HasForeignKey("AllocationRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BudgetManagement.Domain.Entities.BudgetGroup", "ParentBudgetGroup")
                        .WithMany()
                        .HasForeignKey("ParentBudgetGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AllocationRule");

                    b.Navigation("ParentBudgetGroup");
                });

            modelBuilder.Entity("BudgetManagement.Domain.Entities.BudgetRequest", b =>
                {
                    b.HasOne("BudgetManagement.Domain.Entities.MiscMaster", "MiscRequestBy")
                        .WithMany("BudgetRequestBy")
                        .HasForeignKey("RequestById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BudgetManagement.Domain.Entities.MiscMaster", "MiscRequestMonth")
                        .WithMany("BudgetRequestMonth")
                        .HasForeignKey("RequestMonthId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BudgetManagement.Domain.Entities.MiscMaster", "MiscRequestType")
                        .WithMany("BudgetRequests")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MiscRequestBy");

                    b.Navigation("MiscRequestMonth");

                    b.Navigation("MiscRequestType");
                });

            modelBuilder.Entity("BudgetManagement.Domain.Entities.MiscMaster", b =>
                {
                    b.HasOne("BudgetManagement.Domain.Entities.MiscTypeMaster", "MiscTypeMaster")
                        .WithMany("MiscMaster")
                        .HasForeignKey("MiscTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MiscTypeMaster");
                });

            modelBuilder.Entity("BudgetManagement.Domain.Entities.BudgetGroup", b =>
                {
                    b.Navigation("BudgetAllocationGroupType");
                });

            modelBuilder.Entity("BudgetManagement.Domain.Entities.BudgetRequest", b =>
                {
                    b.Navigation("BudgetAllocationRequestType");
                });

            modelBuilder.Entity("BudgetManagement.Domain.Entities.MiscMaster", b =>
                {
                    b.Navigation("BudgetAllocationRules");

                    b.Navigation("BudgetAllocationType");

                    b.Navigation("BudgetRequestBy");

                    b.Navigation("BudgetRequestByType");

                    b.Navigation("BudgetRequestMonth");

                    b.Navigation("BudgetRequestMonthType");

                    b.Navigation("BudgetRequests");
                });

            modelBuilder.Entity("BudgetManagement.Domain.Entities.MiscTypeMaster", b =>
                {
                    b.Navigation("MiscMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
