using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using ProjectManagement.Application.ProjectWorkBreakdownStructure.Command.CreateProjectWorkBreakdownStructureCommand;
using ProjectManagement.Application.ProjectWorkBreakdownStructure.Command.UpdateProjectWorkBreakdownStructureCommand;
using ProjectManagement.Application.ProjectWorkBreakdownStructure.Queries.Dtos;

namespace ProjectManagement.Application.Common.Mappings
{
    public class ProjectWorkBreakdownStructureProfile : Profile
    {

        public ProjectWorkBreakdownStructureProfile()
        {
            // CreateMap<CreateProjectWorkBreakdownStructureCommand, ProjectManagement.Domain.Entities.ProjectWorkBreakdownStructure>()
            // .ForMember(d => d.Id, opt => opt.Ignore()) // Id is generated by DB
            // .ForMember(d => d.Level, opt => opt.MapFrom(src => 1)) // default or calculate based on parent
            // .ForMember(d => d.UnitId, opt => opt.Ignore())
            // .ForMember(d => d.BudgetYearId, opt => opt.Ignore());

            CreateMap<CreateProjectWorkBreakdownStructureCommand, ProjectManagement.Domain.Entities.ProjectWorkBreakdownStructure>();

            CreateMap<ProjectManagement.Domain.Entities.ProjectWorkBreakdownStructure, ProjectWorkBreakdownStructureDto>()
                .ForMember(d => d.ProjectCode,
                    opt => opt.MapFrom(s => s.Project.ProjectCode))
                .ForMember(d => d.ParentWorkBreakdownStructureName,
                    opt => opt.MapFrom(s => s.ParentWorkBreakdownStructure != null
                        ? s.ParentWorkBreakdownStructure.WorkBreakdownStructureName
                        : null));
                        


             // UPDATE: Command -> Entity
        CreateMap<UpdateProjectWorkBreakdownStructureCommand, ProjectManagement.Domain.Entities.ProjectWorkBreakdownStructure>()
            .ForMember(d => d.Id,            opt => opt.Ignore())      // don't overwrite PK
            .ForMember(d => d.ProjectId,     opt => opt.Ignore())      // keep from existing entity
            .ForMember(d => d.Level,         opt => opt.Ignore())      // we calculate
            .ForMember(d => d.DurationInDays,opt => opt.Ignore())      // we calculate
            .ForMember(d => d.UnitId,        opt => opt.Ignore())      // inherited from Project
            .ForMember(d => d.BudgetYearId,  opt => opt.Ignore())      // inherited from Project
            .ForMember(d => d.CurrencyId,    opt => opt.Ignore())      // inherited from Project
            .ForMember(d => d.IsDeleted,     opt => opt.Ignore())
            .ForMember(d => d.IsActive,      opt => opt.Ignore());

        // Entity -> DTO
        CreateMap<ProjectManagement.Domain.Entities.ProjectWorkBreakdownStructure, ProjectWorkBreakdownStructureDto>()
            .ForMember(d => d.ProjectCode, opt => opt.MapFrom(src => src.Project.ProjectCode))
            .ForMember(d => d.UnitName,    opt => opt.Ignore())
            .ForMember(d => d.CurrencyName,opt => opt.Ignore())
            .ForMember(d => d.CostCenterName, opt => opt.Ignore())
            .ForMember(d => d.ResponsibleDepartment, opt => opt.Ignore());

        }
    }
}