global using System.Net;
global using System.Net.Http.Headers;
global using System.Net.Http.Json;
global using System.Text.Json;
global using FluentAssertions;
global using Microsoft.Extensions.Configuration;
global using Xunit;
global using Shared.QAInfrastructure.Fixtures;
global using Shared.QAInfrastructure.Infrastructure;
