// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesManagement.Infrastructure.Data;

#nullable disable

namespace SalesManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220114450_SalesSegmentMaster")]
    partial class SalesSegmentMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesManagement.Domain.Entities.BusinessUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessUnitCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BusinessUnitName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitCode")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.ToTable("BusinessUnit", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.Property<string>("SalesChannelCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SalesChannelCode");

                    b.Property<string>("SalesChannelName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SalesChannelName");

                    b.HasKey("Id");

                    b.HasIndex("SalesChannelCode")
                        .IsUnique();

                    b.ToTable("SalesChannel", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesOrganisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.Property<string>("SalesOrganisationCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SalesOrganisationCode");

                    b.Property<string>("SalesOrganisationName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SalesOrganisationName");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SalesOrganisationCode")
                        .IsUnique();

                    b.ToTable("SalesOrganisation", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessUnitId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalesChannelId")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("SalesChannelId");

                    b.HasIndex("SalesOrganisationId");

                    b.HasIndex("SalesOrganisationId", "SalesChannelId", "BusinessUnitId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("SalesSegment", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesSegment", b =>
                {
                    b.HasOne("SalesManagement.Domain.Entities.BusinessUnit", "BusinessUnit")
                        .WithMany("SalesSegments")
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalesManagement.Domain.Entities.SalesChannel", "SalesChannel")
                        .WithMany("SalesSegments")
                        .HasForeignKey("SalesChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalesManagement.Domain.Entities.SalesOrganisation", "SalesOrganisation")
                        .WithMany("SalesSegments")
                        .HasForeignKey("SalesOrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessUnit");

                    b.Navigation("SalesChannel");

                    b.Navigation("SalesOrganisation");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.BusinessUnit", b =>
                {
                    b.Navigation("SalesSegments");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesChannel", b =>
                {
                    b.Navigation("SalesSegments");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesOrganisation", b =>
                {
                    b.Navigation("SalesSegments");
                });
#pragma warning restore 612, 618
        }
    }
}
