// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesManagement.Infrastructure.Data;

#nullable disable

namespace SalesManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesManagement.Domain.Entities.AgentCommissionConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("int")
                        .HasColumnName("AgentId");

                    b.Property<decimal>("CommissionPercentage")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("CommissionPercentage");

                    b.Property<int>("CommissionTypeId")
                        .HasColumnType("int")
                        .HasColumnName("CommissionTypeId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemId");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.Property<int>("SalesSegmentId")
                        .HasColumnType("int")
                        .HasColumnName("SalesSegmentId");

                    b.Property<decimal?>("SubAgentPercentage")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("SubAgentPercentage");

                    b.Property<int?>("UomId")
                        .HasColumnType("int")
                        .HasColumnName("UomId");

                    b.Property<DateTimeOffset>("ValidityFrom")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ValidityFrom");

                    b.Property<DateTimeOffset>("ValidityTo")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ValidityTo");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CommissionTypeId");

                    b.HasIndex("ItemId");

                    b.HasIndex("SalesSegmentId");

                    b.HasIndex("ValidityFrom", "ValidityTo");

                    b.HasIndex("AgentId", "SalesSegmentId", "ItemId");

                    b.ToTable("AgentCommissionConfig", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.BusinessUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessUnitCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BusinessUnitName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitCode")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.ToTable("BusinessUnit", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.MiscMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Code");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MiscTypeId")
                        .HasColumnType("int")
                        .HasColumnName("MiscTypeId");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SortOrder");

                    b.HasKey("Id");

                    b.HasIndex("MiscTypeId");

                    b.HasIndex("MiscTypeId", "Code")
                        .IsUnique();

                    b.ToTable("MiscMaster", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.MiscTypeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("MiscTypeCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MiscTypeCode");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.HasKey("Id");

                    b.HasIndex("MiscTypeCode")
                        .IsUnique();

                    b.ToTable("MiscTypeMaster", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.Property<string>("SalesChannelCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SalesChannelCode");

                    b.Property<string>("SalesChannelName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SalesChannelName");

                    b.HasKey("Id");

                    b.HasIndex("SalesChannelCode")
                        .IsUnique();

                    b.ToTable("SalesChannel", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.Property<int?>("ProductCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("ProductCategoryId");

                    b.Property<string>("RegionTerritory")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RegionTerritory");

                    b.Property<string>("ResponsibleManager")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ResponsibleManager");

                    b.Property<string>("SalesGroupName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SalesGroupName");

                    b.Property<int>("SalesOfficeId")
                        .HasColumnType("int")
                        .HasColumnName("SalesOfficeId");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("SalesOfficeId");

                    b.HasIndex("SalesOfficeId", "SalesGroupName")
                        .IsUnique();

                    b.ToTable("SalesGroup", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesItemPriceMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyId");

                    b.Property<decimal>("ExMillPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("ExMillPrice");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemId");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.Property<int>("PaymentTermsId")
                        .HasColumnType("int")
                        .HasColumnName("PaymentTermsId");

                    b.Property<string>("PriceCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PriceCode");

                    b.Property<int>("SalesSegmentId")
                        .HasColumnType("int")
                        .HasColumnName("SalesSegmentId");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTimeOffset>("ValidTo")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ValidTo");

                    b.HasKey("Id");

                    b.HasIndex("PriceCode")
                        .IsUnique();

                    b.HasIndex("SalesSegmentId");

                    b.HasIndex("ItemId", "SalesSegmentId", "PaymentTermsId");

                    b.ToTable("SalesItemPriceMaster", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Address");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("Pincode")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Pincode");

                    b.Property<string>("RegionTerritory")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RegionTerritory");

                    b.Property<string>("ResponsibleManager")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ResponsibleManager");

                    b.Property<string>("SalesOfficeName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SalesOfficeName");

                    b.Property<int>("SalesOrganisationId")
                        .HasColumnType("int")
                        .HasColumnName("SalesOrganisationId");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("SalesOrganisationId");

                    b.HasIndex("SalesOrganisationId", "SalesOfficeName")
                        .IsUnique();

                    b.ToTable("SalesOffice", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesOrganisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.Property<string>("SalesOrganisationCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SalesOrganisationCode");

                    b.Property<string>("SalesOrganisationName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("SalesOrganisationName");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SalesOrganisationCode")
                        .IsUnique();

                    b.ToTable("SalesOrganisation", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessUnitId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalesChannelId")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("SegmentName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("SalesChannelId");

                    b.HasIndex("SalesOrganisationId");

                    b.HasIndex("SalesOrganisationId", "SalesChannelId", "BusinessUnitId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("SalesSegment", "Sales");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.AgentCommissionConfig", b =>
                {
                    b.HasOne("SalesManagement.Domain.Entities.MiscMaster", "MiscMaster")
                        .WithMany()
                        .HasForeignKey("CommissionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalesManagement.Domain.Entities.SalesSegment", "SalesSegment")
                        .WithMany()
                        .HasForeignKey("SalesSegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MiscMaster");

                    b.Navigation("SalesSegment");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.MiscMaster", b =>
                {
                    b.HasOne("SalesManagement.Domain.Entities.MiscTypeMaster", "MiscTypeMaster")
                        .WithMany("MiscMasters")
                        .HasForeignKey("MiscTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MiscTypeMaster");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesGroup", b =>
                {
                    b.HasOne("SalesManagement.Domain.Entities.SalesOffice", "SalesOffice")
                        .WithMany("SalesGroups")
                        .HasForeignKey("SalesOfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SalesOffice");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesItemPriceMaster", b =>
                {
                    b.HasOne("SalesManagement.Domain.Entities.SalesSegment", "SalesSegment")
                        .WithMany()
                        .HasForeignKey("SalesSegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SalesSegment");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesOffice", b =>
                {
                    b.HasOne("SalesManagement.Domain.Entities.SalesOrganisation", "SalesOrganisation")
                        .WithMany("SalesOffices")
                        .HasForeignKey("SalesOrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SalesOrganisation");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesSegment", b =>
                {
                    b.HasOne("SalesManagement.Domain.Entities.BusinessUnit", "BusinessUnit")
                        .WithMany("SalesSegments")
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalesManagement.Domain.Entities.SalesChannel", "SalesChannel")
                        .WithMany("SalesSegments")
                        .HasForeignKey("SalesChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalesManagement.Domain.Entities.SalesOrganisation", "SalesOrganisation")
                        .WithMany("SalesSegments")
                        .HasForeignKey("SalesOrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessUnit");

                    b.Navigation("SalesChannel");

                    b.Navigation("SalesOrganisation");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.BusinessUnit", b =>
                {
                    b.Navigation("SalesSegments");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.MiscTypeMaster", b =>
                {
                    b.Navigation("MiscMasters");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesChannel", b =>
                {
                    b.Navigation("SalesSegments");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesOffice", b =>
                {
                    b.Navigation("SalesGroups");
                });

            modelBuilder.Entity("SalesManagement.Domain.Entities.SalesOrganisation", b =>
                {
                    b.Navigation("SalesOffices");

                    b.Navigation("SalesSegments");
                });
#pragma warning restore 612, 618
        }
    }
}
