using static Shared.QAInfrastructure.Helpers.QAHelper;

namespace FinanceManagement.QATests.Tests.FinancialYearMaster;

// ─────────────────────────────────────────────────────────────────────────────
// US-GL03-01 — Financial Year & Period Calendar Setup
// Live QA suite against the running BSOFT.Api QA clone.
//
// Conventions (matching the canonical UserManagement.QATests pattern):
//   * Single shared QAServerFixture (one testsales session, run-unique EntityCode).
//   * Steps ordered with [TestPriority(N)] so create runs before update/delete.
//   * GetAll happy-path tagged [Trait("Layer","Smoke")] — deploy-gate slice.
//   * Run-unique year picked from EntityCode → no conflicts across runs.
// ─────────────────────────────────────────────────────────────────────────────

[Collection("FinancialYearMasterCollection")]
[TestCaseOrderer("Shared.QAInfrastructure.Infrastructure.PriorityOrderer", "Shared.QAInfrastructure")]
public sealed class FinancialYearMasterQATests
{
    private readonly QAServerFixture _f;
    private const string BaseRoute = "/api/finance/FinancialYearMaster";

    // Run-unique year derived from the fixture EntityCode — far-future to avoid collisions with
    // real seed data. Band 2100-5099 (3000 slots) keeps the suite re-runnable without a DB reset
    // (a % 100 here left only 100 years, which fill up and collide on a non-reset clone). The band
    // is disjoint from FinancialPeriodStatusQATests (5100-8099) so the two year-creating suites
    // never pick the same fiscal year on a shared clone.
    private int StartYear => 2100 + (RunUniqueInt(_f.EntityCode) % 3000);
    private string Code         => $"{StartYear}-{(StartYear + 1) % 100:D2}";
    private string StartDateStr => $"{StartYear}-04-01";
    private string EndDateStr   => $"{StartYear + 1}-03-31";

    public FinancialYearMasterQATests(QAServerFixture fixture) => _f = fixture;

    // Cross-step id tracking
    private static int _createdId;
    private static int _createdPeriodId;

    // ─────────────────────────────────────────────────────────────────────────
    // SECTION 1 — CREATE (TC001 captures CreatedId)
    // POST api/finance/FinancialYearMaster — body: { financialYearCode, startDate, endDate, isTransitionYear }
    // ─────────────────────────────────────────────────────────────────────────

    [Fact, TestPriority(1)]
    public async Task TC001_Create_HappyPath_Returns200_AndAutoGenerates13Periods()
    {
        var resp = await _f.Client.PostAsJsonAsync(BaseRoute, new
        {
            financialYearCode = Code,
            startDate         = StartDateStr,
            endDate           = EndDateStr,
            isTransitionYear  = false
        });

        await AssertOkAsync(resp);
        _createdId = await GetCreatedIdAsync(resp);
        _createdId.Should().BeGreaterThan(0);

        // Verify 13 periods generated by re-reading the year detail
        var detail = await _f.Client.GetAsync($"{BaseRoute}/{_createdId}");
        await AssertOkAsync(detail);
        using var doc = await ParseAsync(detail);
        var periods = doc.RootElement.GetProperty("data").GetProperty("periods");
        periods.GetArrayLength().Should().Be(13);
    }

    [Fact, TestPriority(2)]
    public async Task TC002_Create_NoAuthToken_Returns401()
    {
        var resp = await _f.AnonymousClient.PostAsJsonAsync(BaseRoute, new
        {
            financialYearCode = $"{StartYear + 100}-{(StartYear + 101) % 100:D2}",
            startDate         = $"{StartYear + 100}-04-01",
            endDate           = $"{StartYear + 101}-03-31"
        });

        await Assert401Async(resp);
    }

    [Fact, TestPriority(3)]
    public async Task TC003_Create_EmptyCode_Returns400()
    {
        var resp = await _f.Client.PostAsJsonAsync(BaseRoute, new
        {
            financialYearCode = "",
            startDate         = StartDateStr,
            endDate           = EndDateStr
        });

        await Assert400Async(resp);
        await AssertBodyContainsAsync(resp, "required");
    }

    [Theory, TestPriority(4)]
    [InlineData("FY24")]            // not numeric format
    [InlineData("2024")]            // missing suffix
    [InlineData("2024-2025")]       // 4-digit suffix
    public async Task TC004_Create_InvalidCodeFormat_Returns400(string badCode)
    {
        var resp = await _f.Client.PostAsJsonAsync(BaseRoute, new
        {
            financialYearCode = badCode,
            startDate         = StartDateStr,
            endDate           = EndDateStr
        });

        await Assert400Async(resp);
        await AssertBodyContainsAsync(resp, "YYYY-YY");
    }

    [Fact, TestPriority(5)]
    public async Task TC005_Create_CodeSuffixMismatchStartYear_Returns400()
    {
        // StartYear=2100 but code says 2024-25
        var resp = await _f.Client.PostAsJsonAsync(BaseRoute, new
        {
            financialYearCode = "2024-25",
            startDate         = StartDateStr,
            endDate           = EndDateStr
        });

        await Assert400Async(resp);
        await AssertBodyContainsAsync(resp, "match Start Date year");
    }

    [Fact, TestPriority(6)]
    public async Task TC006_Create_StartDateNotFirstOfMonth_Returns400()
    {
        var resp = await _f.Client.PostAsJsonAsync(BaseRoute, new
        {
            financialYearCode = Code,
            startDate         = $"{StartYear}-04-15",     // 15th, not 1st
            endDate           = EndDateStr
        });

        await Assert400Async(resp);
        await AssertBodyContainsAsync(resp, "1st of a month");
    }

    [Fact, TestPriority(7)]
    public async Task TC007_Create_NotTransitionYear_NotExactly12Months_Returns400()
    {
        var resp = await _f.Client.PostAsJsonAsync(BaseRoute, new
        {
            financialYearCode = Code,
            startDate         = StartDateStr,
            endDate           = $"{StartYear + 1}-02-28",   // 11 months, not 12
            isTransitionYear  = false
        });

        await Assert400Async(resp);
        await AssertBodyContainsAsync(resp, "exactly 12 months");
    }

    [Fact, TestPriority(8)]
    public async Task TC008_Create_TransitionYear_Allows15Months_Returns200()
    {
        var alt        = StartYear + 50;
        var altCode    = $"{alt}-{(alt + 1) % 100:D2}";
        var altStart   = $"{alt}-04-01";
        var altEnd15Mo = $"{alt + 1}-06-30";

        var resp = await _f.Client.PostAsJsonAsync(BaseRoute, new
        {
            financialYearCode = altCode,
            startDate         = altStart,
            endDate           = altEnd15Mo,
            isTransitionYear  = true
        });

        await AssertOkAsync(resp);

        // Self-clean
        var id = await GetCreatedIdAsync(resp);
        await _f.Client.DeleteAsync($"{BaseRoute}?id={id}");
    }

    [Fact, TestPriority(9)]
    public async Task TC009_Create_DuplicateCode_ForSameCompany_Returns400()
    {
        // TC001 already created Code for this company
        var resp = await _f.Client.PostAsJsonAsync(BaseRoute, new
        {
            financialYearCode = Code,
            startDate         = StartDateStr,
            endDate           = EndDateStr
        });

        await Assert400Async(resp);
        await AssertBodyContainsAsync(resp, "already exists");
    }

    [Fact, TestPriority(10)]
    public async Task TC010_Create_DateRangeOverlapsExisting_Returns400()
    {
        // Overlaps the year created in TC001
        var resp = await _f.Client.PostAsJsonAsync(BaseRoute, new
        {
            financialYearCode = $"{StartYear + 1}-{(StartYear + 2) % 100:D2}",
            startDate         = $"{StartYear}-08-01",       // mid-existing range
            endDate           = $"{StartYear + 1}-07-31"
        });

        await Assert400Async(resp);
        await AssertBodyContainsAsync(resp, "overlap");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // SECTION 2 — GET ALL  (smoke trait on the happy path)
    // ─────────────────────────────────────────────────────────────────────────

    [Fact, TestPriority(11)]
    [Trait("Layer", "Smoke")]
    public async Task TC011_GetAll_HappyPath_Returns200()
    {
        var resp = await _f.Client.GetAsync($"{BaseRoute}?PageNumber=1&PageSize=15");

        await AssertOkAsync(resp);
        using var doc = await ParseAsync(resp);
        doc.RootElement.TryGetProperty("data", out _).Should().BeTrue();
        doc.RootElement.GetProperty("totalCount").GetInt32().Should().BeGreaterThanOrEqualTo(1);
    }

    [Fact, TestPriority(12)]
    public async Task TC012_GetAll_NoAuthToken_Returns401()
    {
        var resp = await _f.AnonymousClient.GetAsync($"{BaseRoute}?PageNumber=1&PageSize=15");
        await Assert401Async(resp);
    }

    [Fact, TestPriority(13)]
    public async Task TC013_GetAll_SearchByCode_Returns200()
    {
        var resp = await _f.Client.GetAsync($"{BaseRoute}?PageNumber=1&PageSize=15&SearchTerm={StartYear}");
        await AssertOkAsync(resp);

        using var doc = await ParseAsync(resp);
        doc.RootElement.GetProperty("data").GetArrayLength().Should().BeGreaterThan(0);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // SECTION 3 — GET BY ID
    // ─────────────────────────────────────────────────────────────────────────

    [Fact, TestPriority(20)]
    public async Task TC020_GetById_ExistingId_Returns200_WithPeriods()
    {
        _createdId.Should().BeGreaterThan(0, "TC001 should have captured an id");

        var resp = await _f.Client.GetAsync($"{BaseRoute}/{_createdId}");
        await AssertOkAsync(resp);

        using var doc = await ParseAsync(resp);
        var data = doc.RootElement.GetProperty("data");
        data.GetProperty("financialYearCode").GetString().Should().Be(Code);
        data.GetProperty("periods").GetArrayLength().Should().Be(13);

        // Capture first period id for downstream tests
        _createdPeriodId = data.GetProperty("periods")[0].GetProperty("id").GetInt32();
    }

    [Fact, TestPriority(21)]
    public async Task TC021_GetById_NonExistent_Returns200_WithNullData()
    {
        var resp = await _f.Client.GetAsync($"{BaseRoute}/999999");
        // BSOFT convention: 200 with null data for unknown ids
        resp.StatusCode.Should().BeOneOf(HttpStatusCode.OK, HttpStatusCode.NotFound);
    }

    [Fact, TestPriority(22)]
    public async Task TC022_GetById_NoAuth_Returns401()
    {
        var resp = await _f.AnonymousClient.GetAsync($"{BaseRoute}/{_createdId}");
        await Assert401Async(resp);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // SECTION 4 — AUTOCOMPLETE
    // ─────────────────────────────────────────────────────────────────────────

    [Fact, TestPriority(30)]
    public async Task TC030_AutoComplete_HappyPath_Returns200()
    {
        var resp = await _f.Client.GetAsync($"{BaseRoute}/by-name?term={StartYear}");
        await AssertOkAsync(resp);
    }

    [Fact, TestPriority(31)]
    public async Task TC031_AutoComplete_EmptyTerm_Returns200()
    {
        var resp = await _f.Client.GetAsync($"{BaseRoute}/by-name?term=");
        await AssertOkAsync(resp);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // SECTION 5 — POSTING-ENGINE READ APIs
    // GET {companyId}/periods + period-for-date
    // ─────────────────────────────────────────────────────────────────────────

    [Fact, TestPriority(40)]
    public async Task TC040_GetPeriodsForCompany_Returns200()
    {
        // testsales operates under CompanyId 0 (first-time-login placeholder), and this suite's
        // TC001 creates the financial year + 13 periods under that company — so the period calendar
        // lives under company 0 on the isolated clone, not the shared-DB "company 1" convention.
        var resp = await _f.Client.GetAsync($"{BaseRoute}/0/periods");
        await AssertOkAsync(resp);

        using var doc = await ParseAsync(resp);
        doc.RootElement.GetProperty("data").GetArrayLength().Should().BeGreaterThan(0);
    }

    [Fact, TestPriority(41)]
    public async Task TC041_GetPeriodForDate_DateInsidePeriod_Returns200_WithPeriod()
    {
        // June 15 of the run-unique start year should resolve to Period 3
        var resp = await _f.Client.GetAsync($"{BaseRoute}/period-for-date?date={StartYear}-06-15");
        await AssertOkAsync(resp);

        using var doc = await ParseAsync(resp);
        var data = doc.RootElement.GetProperty("data");
        if (data.ValueKind == JsonValueKind.Object)
        {
            data.GetProperty("periodNumber").GetInt32().Should().Be(3);
            data.GetProperty("isAdjustmentPeriod").GetBoolean().Should().BeFalse();
        }
    }

    [Fact, TestPriority(42)]
    public async Task TC042_GetPeriodForDate_DateInPeriod12_SkipsAdjustmentPeriod()
    {
        // March 15 of next year — Period 12 (Mar) and Period 13 (adjustment) both span Mar 1-31.
        // The endpoint must skip the adjustment period and return regular Period 12.
        var resp = await _f.Client.GetAsync($"{BaseRoute}/period-for-date?date={StartYear + 1}-03-15");
        await AssertOkAsync(resp);

        using var doc = await ParseAsync(resp);
        var data = doc.RootElement.GetProperty("data");
        if (data.ValueKind == JsonValueKind.Object)
        {
            data.GetProperty("periodNumber").GetInt32().Should().Be(12);
            data.GetProperty("isAdjustmentPeriod").GetBoolean().Should().BeFalse();
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // SECTION 6 — UPDATE
    // ─────────────────────────────────────────────────────────────────────────

    [Fact, TestPriority(50)]
    public async Task TC050_Update_HappyPath_Returns200()
    {
        _createdId.Should().BeGreaterThan(0);

        var resp = await _f.Client.PutAsJsonAsync(BaseRoute, new
        {
            id = _createdId,
            financialYearCode = Code,    // same code, just touch the row
            isActive = 1
        });

        await AssertOkAsync(resp);
    }

    [Fact, TestPriority(51)]
    public async Task TC051_Update_NotFoundId_Returns400()
    {
        var resp = await _f.Client.PutAsJsonAsync(BaseRoute, new
        {
            id = 999999,
            financialYearCode = "9999-00",
            isActive = 1
        });

        await Assert400Async(resp);
    }

    [Theory, TestPriority(52)]
    [InlineData(2)]
    [InlineData(-1)]
    public async Task TC052_Update_IsActiveOutOfRange_Returns400(int isActive)
    {
        var resp = await _f.Client.PutAsJsonAsync(BaseRoute, new
        {
            id = _createdId,
            financialYearCode = Code,
            isActive
        });

        await Assert400Async(resp);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // SECTION 7 — DEACTIVATE (Update IsActive=0, NOT delete)
    // ─────────────────────────────────────────────────────────────────────────

    [Fact, TestPriority(60)]
    public async Task TC060_Deactivate_Update_IsActive0_Returns200()
    {
        _createdId.Should().BeGreaterThan(0);

        var resp = await _f.Client.PutAsJsonAsync(BaseRoute, new
        {
            id = _createdId,
            financialYearCode = Code,
            isActive = 0
        });

        await AssertOkAsync(resp);
    }

    [Fact, TestPriority(61)]
    public async Task TC061_Deactivate_Re_Activate_Returns200()
    {
        var resp = await _f.Client.PutAsJsonAsync(BaseRoute, new
        {
            id = _createdId,
            financialYearCode = Code,
            isActive = 1
        });

        await AssertOkAsync(resp);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // SECTION 8 — DELETE (soft) + already-deleted guard
    // ─────────────────────────────────────────────────────────────────────────

    [Fact, TestPriority(80)]
    public async Task TC080_Delete_HappyPath_Returns200()
    {
        _createdId.Should().BeGreaterThan(0);

        var resp = await _f.Client.DeleteAsync($"{BaseRoute}?id={_createdId}");
        await AssertOkAsync(resp);
    }

    [Fact, TestPriority(81)]
    public async Task TC081_Delete_AlreadyDeleted_Returns400()
    {
        // TC080 already soft-deleted _createdId
        var resp = await _f.Client.DeleteAsync($"{BaseRoute}?id={_createdId}");
        // Server may return 400 (validator says NotFound) or 200 with isSuccess=false
        resp.StatusCode.Should().BeOneOf(HttpStatusCode.OK, HttpStatusCode.BadRequest);
    }

    [Fact, TestPriority(82)]
    public async Task TC082_Delete_NonExistent_Returns400()
    {
        var resp = await _f.Client.DeleteAsync($"{BaseRoute}?id=999999");
        resp.StatusCode.Should().BeOneOf(HttpStatusCode.OK, HttpStatusCode.BadRequest);
    }
}
