global using System.Net;
global using System.Net.Http.Json;
global using System.Text.Json;
global using FluentAssertions;
global using Xunit;
global using Shared.QAInfrastructure.Fixtures;
global using Shared.QAInfrastructure.Infrastructure;
global using Shared.QAInfrastructure.Helpers;
global using FixedAssetManagement.FunctionalTests.Fixtures;
