// <auto-generated />
using System;
using BackgroundService.Infrastructure.Data.Notification;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackgroundService.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20250917080306_workflowtypeColumnadd")]
    partial class workflowtypeColumnadd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.MiscMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Code");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MiscTypeId")
                        .HasColumnType("int")
                        .HasColumnName("MiscTypeId");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sortOrder");

                    b.HasKey("Id");

                    b.HasIndex("MiscTypeId");

                    b.ToTable("MiscMaster", "AppData");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.MiscTypeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("MiscTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MiscTypeCode");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("MiscTypeMaster", "AppData");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("Varchar(250)")
                        .HasColumnName("ModuleName");

                    b.Property<int>("NotificationEventTypeId")
                        .HasColumnType("int")
                        .HasColumnName("NotificationEventTypeId");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id");

                    b.HasIndex("NotificationEventTypeId");

                    b.ToTable("NotificationConfig", "AppNotification");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationEventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionStatus")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("MessageText")
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NotificationLevelRuleId")
                        .HasColumnType("int")
                        .HasColumnName("NotificationLevelRuleId");

                    b.Property<int>("NotificationStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ReadStatusId")
                        .HasColumnType("int");

                    b.Property<string>("SendTo")
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("NotificationLevelRuleId");

                    b.HasIndex("NotificationStatusId");

                    b.HasIndex("ReadStatusId");

                    b.ToTable("NotificationEventLog", "AppNotification");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationEventRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NotificationChannelId")
                        .HasColumnType("int")
                        .HasColumnName("NotificationChannelId");

                    b.Property<int>("NotificationLevelHierarchyId")
                        .HasColumnType("int")
                        .HasColumnName("NotificationLevelHierarchyId");

                    b.Property<int>("RecipientTypeId")
                        .HasColumnType("int")
                        .HasColumnName("RecipientTypeId");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("TemplateId");

                    b.HasKey("Id");

                    b.HasIndex("NotificationChannelId");

                    b.HasIndex("NotificationLevelHierarchyId");

                    b.HasIndex("RecipientTypeId");

                    b.HasIndex("TemplateId");

                    b.ToTable("NotificationEventRule", "AppNotification");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("Varchar(250)")
                        .HasColumnName("GroupName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id");

                    b.ToTable("NotificationGroup", "AppNotification");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationGroupMembers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("NotificationGroupMembers", "AppNotification");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationLevelHierarchy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalModeId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalModeId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("Varchar(Max)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NotificationConfigId")
                        .HasColumnType("int")
                        .HasColumnName("NotificationConfigId");

                    b.Property<int>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("TargetId");

                    b.Property<int>("TargetTypeId")
                        .HasColumnType("int")
                        .HasColumnName("TargetTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalModeId");

                    b.HasIndex("NotificationConfigId");

                    b.HasIndex("TargetTypeId");

                    b.ToTable("NotificationLevelHierarchy", "AppNotification");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationTablePreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PresetKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PresetKey")
                        .IsUnique()
                        .HasDatabaseName("UX_TablePresets_PresetKey");

                    b.HasIndex("TemplateId");

                    b.ToTable("NotificationTablePreset", "Notification", t =>
                        {
                            t.HasCheckConstraint("CK_TablePresets_ColumnsJson_IsJson", "ISJSON([ColumnsJson]) = 1");
                        });
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("NVarchar(Max)")
                        .HasColumnName("BodyTemplate");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FooterTemplate")
                        .IsRequired()
                        .HasColumnType("NVarchar(Max)")
                        .HasColumnName("FooterTemplate");

                    b.Property<string>("HeaderTemplate")
                        .IsRequired()
                        .HasColumnType("NVarchar(Max)")
                        .HasColumnName("HeaderTemplate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsTable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("LanguageCode");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NotificationConfigId")
                        .HasColumnType("int")
                        .HasColumnName("NotificationConfigId");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int")
                        .HasColumnName("NotificationTypeId");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasColumnType("NVarchar(Max)")
                        .HasColumnName("SubjectTemplate");

                    b.HasKey("Id");

                    b.HasIndex("NotificationConfigId");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("NotificationTemplate", "AppNotification");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalDataField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FieldKey");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("JsonPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("JsonPath");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Scope");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ValueType");

                    b.HasKey("Id");

                    b.ToTable("ApprovalDataField", "AppData");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalRequestId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalRequestId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FileName");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FilePath");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalRequestId");

                    b.ToTable("ApprovalDocument", "AppData");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("Action");

                    b.Property<int?>("ApprovalRuleId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalRuleId");

                    b.Property<int>("ApprovalStepDetailId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalStepDetailId");

                    b.Property<string>("ApproverBinding")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ApproverBinding");

                    b.Property<string>("ApproverValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ApproverValue");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentId");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ModuleTransactionId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleTransactionId");

                    b.Property<string>("Remark")
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("Remark");

                    b.Property<DateTimeOffset>("RequestedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("RequestedDate");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("WorkflowType");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalRuleId");

                    b.HasIndex("ApprovalStepDetailId");

                    b.HasIndex("StatusId");

                    b.ToTable("ApprovalRequest", "AppData");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalRequestLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalRequestId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalRequestId");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ModuleLineTransactionId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleLineTransactionId");

                    b.Property<string>("Remark")
                        .HasColumnType("Varchar(max)")
                        .HasColumnName("Remark");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalRequestId");

                    b.HasIndex("StatusId");

                    b.ToTable("ApprovalRequestLine", "AppData");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Action");

                    b.Property<int>("ApprovalStepDetailId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalStepDetailId");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("EffectiveFrom");

                    b.Property<DateOnly>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("EffectiveTo");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("Priority");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<int>("WorkflowTypeId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStepDetailId");

                    b.HasIndex("WorkflowTypeId");

                    b.ToTable("ApprovalRule", "AppData");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalRuleCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aggregate")
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Aggregate");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FieldId")
                        .HasColumnType("int")
                        .HasColumnName("FieldId");

                    b.Property<int>("GroupKey")
                        .HasColumnType("int")
                        .HasColumnName("GroupKey");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Operator");

                    b.Property<string>("RightType")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("RightType");

                    b.Property<string>("RightValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("RightValue");

                    b.Property<int>("RuleId")
                        .HasColumnType("int")
                        .HasColumnName("RuleId");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("RuleId");

                    b.ToTable("ApprovalRuleCondition", "AppData");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalStepDepartmentMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStepDetailId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalStepDetailId");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentId");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStepDetailId");

                    b.ToTable("ApprovalStepDepartmentMapping", "AppData");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalStepDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStepId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalStepId");

                    b.Property<string>("Binding")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Binding");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("MiscMasterId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int")
                        .HasColumnName("StepOrder");

                    b.Property<bool>("StopOnFirstMatch")
                        .HasColumnType("bit")
                        .HasColumnName("StopOnFirstMatch");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Value");

                    b.Property<int>("WorkFlowTypeId")
                        .HasColumnType("int")
                        .HasColumnName("WorkFlowTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStepId");

                    b.HasIndex("MiscMasterId");

                    b.HasIndex("WorkFlowTypeId");

                    b.ToTable("ApprovalStepDetail", "AppData");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalStepUnitMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStepDetailId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovalStepDetailId");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStepDetailId");

                    b.ToTable("ApprovalStepUnitMapping", "AppData");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.RuleTargetOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Binding")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Binding");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RuleId")
                        .HasColumnType("int")
                        .HasColumnName("RuleId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("RuleTargetOverride", "AppData");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.WorkflowType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedIP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsLineLevelApproval")
                        .HasColumnType("bit")
                        .HasColumnName("IsLineLevelApproval");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleId");

                    b.Property<string>("ModuleTypeName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModuleTypeName");

                    b.HasKey("Id");

                    b.ToTable("WorkflowType", "AppData");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.MiscMaster", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscTypeMaster", "MiscType")
                        .WithMany("MiscMaster")
                        .HasForeignKey("MiscTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MiscType");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationConfig", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscMaster", "NotificationEventType")
                        .WithMany("NotificationEventType")
                        .HasForeignKey("NotificationEventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationEventType");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationEventLog", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscMaster", "Channel")
                        .WithMany("Channel")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackgroundService.Domain.Entities.Notification.NotificationEventRule", "NotificationEventRules")
                        .WithMany("NotificationEventLog")
                        .HasForeignKey("NotificationLevelRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscMaster", "NotificationStatus")
                        .WithMany("NotificationStatus")
                        .HasForeignKey("NotificationStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscMaster", "ReadStatus")
                        .WithMany("ReadStatus")
                        .HasForeignKey("ReadStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("NotificationEventRules");

                    b.Navigation("NotificationStatus");

                    b.Navigation("ReadStatus");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationEventRule", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscMaster", "Channel")
                        .WithMany("Channels")
                        .HasForeignKey("NotificationChannelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackgroundService.Domain.Entities.Notification.NotificationLevelHierarchy", "NotificationLevelHierarchy")
                        .WithMany("NotificationEventRules")
                        .HasForeignKey("NotificationLevelHierarchyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscMaster", "RecipientType")
                        .WithMany("RecipientType")
                        .HasForeignKey("RecipientTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackgroundService.Domain.Entities.Notification.NotificationTemplate", "NotificationTemplates")
                        .WithMany("NotificationEventRules")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("NotificationLevelHierarchy");

                    b.Navigation("NotificationTemplates");

                    b.Navigation("RecipientType");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationGroupMembers", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Notification.NotificationGroup", "Group")
                        .WithMany("NotificationGroupMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationLevelHierarchy", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscMaster", "ApprovalMode")
                        .WithMany("ApprovalMode")
                        .HasForeignKey("ApprovalModeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackgroundService.Domain.Entities.Notification.NotificationConfig", "NotificationConfig")
                        .WithMany("NotificationLevelHierarchies")
                        .HasForeignKey("NotificationConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscMaster", "TargetType")
                        .WithMany("TargetType")
                        .HasForeignKey("TargetTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovalMode");

                    b.Navigation("NotificationConfig");

                    b.Navigation("TargetType");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationTablePreset", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Notification.NotificationTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationTemplate", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Notification.NotificationConfig", "NotificationConfig")
                        .WithMany("NotificationTemplates")
                        .HasForeignKey("NotificationConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscMaster", "NotificationType")
                        .WithMany("NotificationTemplates")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationConfig");

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalDocument", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Workflow.ApprovalRequest", "ApprovalRequest")
                        .WithMany("ApprovalDocuments")
                        .HasForeignKey("ApprovalRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovalRequest");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalRequest", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Workflow.ApprovalRule", "ApprovalRule")
                        .WithMany("ApprovalRequest")
                        .HasForeignKey("ApprovalRuleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BackgroundService.Domain.Entities.Workflow.ApprovalStepDetail", "ApprovalStepDetail")
                        .WithMany("ApprovalRequest")
                        .HasForeignKey("ApprovalStepDetailId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscMaster", "Status")
                        .WithMany("ApprovalRequestStatus")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovalRule");

                    b.Navigation("ApprovalStepDetail");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalRequestLine", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Workflow.ApprovalRequest", "ApprovalRequest")
                        .WithMany("ApprovalRequestLines")
                        .HasForeignKey("ApprovalRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscMaster", "Status")
                        .WithMany("ApprovalRequestLineStatus")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovalRequest");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalRule", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Workflow.ApprovalStepDetail", "ApprovalStepDetail")
                        .WithMany("ApprovalRules")
                        .HasForeignKey("ApprovalStepDetailId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackgroundService.Domain.Entities.Workflow.WorkflowType", "WorkflowType")
                        .WithMany("ApprovalRules")
                        .HasForeignKey("WorkflowTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovalStepDetail");

                    b.Navigation("WorkflowType");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalRuleCondition", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Workflow.ApprovalDataField", "Field")
                        .WithMany("Conditions")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackgroundService.Domain.Entities.Workflow.ApprovalRule", "Rule")
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalStepDepartmentMapping", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Workflow.ApprovalStepDetail", "ApprovalStepDetail")
                        .WithMany("ApprovalStepDepartmentMappings")
                        .HasForeignKey("ApprovalStepDetailId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovalStepDetail");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalStepDetail", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscMaster", "ApprovalStep")
                        .WithMany("ApprovalStep")
                        .HasForeignKey("ApprovalStepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BackgroundService.Domain.Entities.Notification.MiscMaster", null)
                        .WithMany("ApprovalType")
                        .HasForeignKey("MiscMasterId");

                    b.HasOne("BackgroundService.Domain.Entities.Workflow.WorkflowType", "WorkflowType")
                        .WithMany("ApprovalStepDetails")
                        .HasForeignKey("WorkFlowTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovalStep");

                    b.Navigation("WorkflowType");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalStepUnitMapping", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Workflow.ApprovalStepDetail", "ApprovalStepDetail")
                        .WithMany("ApprovalStepUnitMappings")
                        .HasForeignKey("ApprovalStepDetailId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovalStepDetail");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.RuleTargetOverride", b =>
                {
                    b.HasOne("BackgroundService.Domain.Entities.Workflow.ApprovalRule", "Rule")
                        .WithMany("RuleTargetOverride")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.MiscMaster", b =>
                {
                    b.Navigation("ApprovalMode");

                    b.Navigation("ApprovalRequestLineStatus");

                    b.Navigation("ApprovalRequestStatus");

                    b.Navigation("ApprovalStep");

                    b.Navigation("ApprovalType");

                    b.Navigation("Channel");

                    b.Navigation("Channels");

                    b.Navigation("NotificationEventType");

                    b.Navigation("NotificationStatus");

                    b.Navigation("NotificationTemplates");

                    b.Navigation("ReadStatus");

                    b.Navigation("RecipientType");

                    b.Navigation("TargetType");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.MiscTypeMaster", b =>
                {
                    b.Navigation("MiscMaster");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationConfig", b =>
                {
                    b.Navigation("NotificationLevelHierarchies");

                    b.Navigation("NotificationTemplates");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationEventRule", b =>
                {
                    b.Navigation("NotificationEventLog");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationGroup", b =>
                {
                    b.Navigation("NotificationGroupMembers");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationLevelHierarchy", b =>
                {
                    b.Navigation("NotificationEventRules");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Notification.NotificationTemplate", b =>
                {
                    b.Navigation("NotificationEventRules");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalDataField", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalRequest", b =>
                {
                    b.Navigation("ApprovalDocuments");

                    b.Navigation("ApprovalRequestLines");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalRule", b =>
                {
                    b.Navigation("ApprovalRequest");

                    b.Navigation("Conditions");

                    b.Navigation("RuleTargetOverride");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.ApprovalStepDetail", b =>
                {
                    b.Navigation("ApprovalRequest");

                    b.Navigation("ApprovalRules");

                    b.Navigation("ApprovalStepDepartmentMappings");

                    b.Navigation("ApprovalStepUnitMappings");
                });

            modelBuilder.Entity("BackgroundService.Domain.Entities.Workflow.WorkflowType", b =>
                {
                    b.Navigation("ApprovalRules");

                    b.Navigation("ApprovalStepDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
