using Contracts.Interfaces.Lookups.Finance;
using Microsoft.EntityFrameworkCore;
using PurchaseManagement.Application.Common.Interfaces.IMiscMaster;
using PurchaseManagement.Domain.Common;
using PurchaseManagement.Domain.Entities.FreightRfq;
using PurchaseManagement.Infrastructure.Data;
using PurchaseManagement.Infrastructure.Repositories.FreightRfq;
using PurchaseManagement.Infrastructure.Repositories.MiscMaster;
using PurchaseManagement.Infrastructure.Repositories.MiscTypeMaster;
using PurchaseManagement.IntegrationTests.Common;
using static PurchaseManagement.Domain.Common.BaseEntity;

namespace PurchaseManagement.IntegrationTests.Repositories.FreightRfq
{
    [Collection("DatabaseCollection")]
    public sealed class FreightRfqCommandRepositoryTests
    {
        private readonly DbFixture _fixture;
        private readonly Mock<IDocumentSequenceLookup> _docSeqMock = new(MockBehavior.Loose);
        private readonly Mock<IMiscMasterQueryRepository> _miscMock = new(MockBehavior.Loose);

        private const int TransactionTypeId = 59;
        private static readonly DateTimeOffset RfqDate = new(2025, 6, 6, 0, 0, 0, TimeSpan.Zero);

        public FreightRfqCommandRepositoryTests(DbFixture fixture)
        {
            _fixture = fixture;
        }

        private FreightRfqCommandRepository CreateRepo(ApplicationDbContext ctx) =>
            new(ctx, _docSeqMock.Object, _miscMock.Object);

        private sealed record Seeded(int PoBasedId, int QuotationPendingId, int PendingId, int ApprovedId, int RejectedId, int PerMtId);

        private async Task<Seeded> SeedMiscAsync(ApplicationDbContext ctx)
        {
            await _fixture.ClearAllTablesAsync();
            var typeRepo = new MiscTypeMasterCommandRepository(ctx);
            var miscRepo = new MiscMasterCommandRepository(ctx);

            async Task<int> Misc(int typeId, string code) =>
                (await miscRepo.CreateAsync(new PurchaseManagement.Domain.Entities.MiscMaster
                { MiscTypeId = typeId, Code = code, Description = code, IsActive = Status.Active, IsDeleted = IsDelete.NotDeleted })).Id;

            var typeType = (await typeRepo.CreateAsync(new PurchaseManagement.Domain.Entities.MiscTypeMaster
            { MiscTypeCode = MiscEnumEntity.FreightRfqType, Description = "Freight RFQ Type", IsActive = Status.Active, IsDeleted = IsDelete.NotDeleted })).Id;
            var statusType = (await typeRepo.CreateAsync(new PurchaseManagement.Domain.Entities.MiscTypeMaster
            { MiscTypeCode = MiscEnumEntity.FreightRfqStatus, Description = "Freight RFQ Status", IsActive = Status.Active, IsDeleted = IsDelete.NotDeleted })).Id;
            var basisType = (await typeRepo.CreateAsync(new PurchaseManagement.Domain.Entities.MiscTypeMaster
            { MiscTypeCode = MiscEnumEntity.FreightRateBasis, Description = "Freight Rate Basis", IsActive = Status.Active, IsDeleted = IsDelete.NotDeleted })).Id;

            var poBased = await Misc(typeType, MiscEnumEntity.FreightRfqTypePoBased);
            var quotationPending = await Misc(statusType, MiscEnumEntity.FreightRfqQuotationPending);
            var pending = await Misc(statusType, MiscEnumEntity.Pending);
            var approved = await Misc(statusType, MiscEnumEntity.Approved);
            var rejected = await Misc(statusType, MiscEnumEntity.Rejected);
            var perMt = await Misc(basisType, MiscEnumEntity.FreightRateBasisPerMt);

            async Task<PurchaseManagement.Domain.Entities.MiscMaster> Load(int id) =>
                await ctx.MiscMaster.AsNoTracking().FirstAsync(m => m.Id == id);

            _miscMock.Setup(m => m.GetMiscMasterByName(MiscEnumEntity.FreightRfqStatus, MiscEnumEntity.FreightRfqQuotationPending)).ReturnsAsync(await Load(quotationPending));
            _miscMock.Setup(m => m.GetMiscMasterByName(MiscEnumEntity.FreightRfqStatus, MiscEnumEntity.Pending)).ReturnsAsync(await Load(pending));
            _miscMock.Setup(m => m.GetMiscMasterByName(MiscEnumEntity.FreightRfqStatus, MiscEnumEntity.Approved)).ReturnsAsync(await Load(approved));
            _miscMock.Setup(m => m.GetMiscMasterByName(MiscEnumEntity.FreightRfqStatus, MiscEnumEntity.Rejected)).ReturnsAsync(await Load(rejected));

            return new Seeded(poBased, quotationPending, pending, approved, rejected, perMt);
        }

        // The document number is generated by the handler now; the repo just persists it.
        private FreightRfqHeader BuildHeader(int rfqTypeId, string number = "FRFQ/2025/0001") => new()
        {
            FreightRfqNumber = number,
            RfqDate = RfqDate,
            RfqTypeId = rfqTypeId,
            SupplierId = 5,
            SourceLocation = "Adilabad",
            SourceStation = "Adilabad Yard",
            DestinationLocation = "Dindigul",
            DestinationStation = "Dindigul Mill Gate",
            TotalQuantity = 120.5m,
            TotalBaleCount = 700,
            IsActive = Status.Active,
            IsDeleted = IsDelete.NotDeleted
        };

        // Newly-added transporter rows (Id = 0) with quoted rates entered.
        private static List<FreightRfqQuotation> TwoQuotes(int perMtId) => new()
        {
            new() { TransporterId = 101, RateBasisId = perMtId, QuotedRate = 5000m, IsActive = Status.Active, IsDeleted = IsDelete.NotDeleted },
            new() { TransporterId = 102, RateBasisId = perMtId, QuotedRate = 2000m, IsActive = Status.Active, IsDeleted = IsDelete.NotDeleted }
        };

        [Fact]
        public async Task CreateAsync_Should_Persist_Number_And_QuotationPendingStatus()
        {
            await using var ctx = _fixture.CreateFreshDbContext();
            var s = await SeedMiscAsync(ctx);

            var id = await CreateRepo(ctx).CreateAsync(BuildHeader(s.PoBasedId), TransactionTypeId, CancellationToken.None);
            ctx.ChangeTracker.Clear();

            var saved = await ctx.FreightRfqHeaders.FirstAsync(x => x.Id == id);
            saved.FreightRfqNumber.Should().Be("FRFQ/2025/0001");
            saved.StatusId.Should().Be(s.QuotationPendingId);
        }

        [Fact]
        public async Task SaveQuotationsAsync_Should_Compute_FreightValue_PerMt()
        {
            await using var ctx = _fixture.CreateFreshDbContext();
            var s = await SeedMiscAsync(ctx);
            var id = await CreateRepo(ctx).CreateAsync(BuildHeader(s.PoBasedId), TransactionTypeId, CancellationToken.None);
            ctx.ChangeTracker.Clear();

            await CreateRepo(ctx).SaveQuotationsAsync(id, TwoQuotes(s.PerMtId));
            ctx.ChangeTracker.Clear();

            var rows = await ctx.FreightRfqQuotations.Where(q => q.FreightRfqHeaderId == id).OrderBy(q => q.QuotedRate).ToListAsync();
            rows.Should().HaveCount(2);
            // Per MT => TotalQuantity (120.5) × rate
            rows.First(r => r.QuotedRate == 2000m).FreightValue.Should().Be(120.5m * 2000m);
            rows.First(r => r.QuotedRate == 5000m).FreightValue.Should().Be(120.5m * 5000m);
        }

        [Fact]
        public async Task SubmitForApprovalAsync_Should_Set_Pending_And_MarkSelected()
        {
            await using var ctx = _fixture.CreateFreshDbContext();
            var s = await SeedMiscAsync(ctx);
            var id = await CreateRepo(ctx).CreateAsync(BuildHeader(s.PoBasedId), TransactionTypeId, CancellationToken.None);
            ctx.ChangeTracker.Clear();
            await CreateRepo(ctx).SaveQuotationsAsync(id, TwoQuotes(s.PerMtId));
            ctx.ChangeTracker.Clear();

            var chosen = await ctx.FreightRfqQuotations.Where(q => q.FreightRfqHeaderId == id).OrderByDescending(q => q.QuotedRate).FirstAsync();
            await CreateRepo(ctx).SubmitForApprovalAsync(id, chosen.Id, isOverride: true, "Reliable carrier");
            ctx.ChangeTracker.Clear();

            var header = await ctx.FreightRfqHeaders.FirstAsync(x => x.Id == id);
            header.StatusId.Should().Be(s.PendingId);
            header.SelectedQuotationId.Should().Be(chosen.Id);

            var selectedRow = await ctx.FreightRfqQuotations.FirstAsync(q => q.Id == chosen.Id);
            selectedRow.IsSelected.Should().BeTrue();
            selectedRow.IsOverride.Should().BeTrue();
        }

        [Fact]
        public async Task ApproveAsync_Should_Snapshot_SelectedQuote_And_SetApproved()
        {
            await using var ctx = _fixture.CreateFreshDbContext();
            var s = await SeedMiscAsync(ctx);
            var id = await CreateRepo(ctx).CreateAsync(BuildHeader(s.PoBasedId), TransactionTypeId, CancellationToken.None);
            ctx.ChangeTracker.Clear();
            await CreateRepo(ctx).SaveQuotationsAsync(id, TwoQuotes(s.PerMtId));
            ctx.ChangeTracker.Clear();
            var chosen = await ctx.FreightRfqQuotations.Where(q => q.FreightRfqHeaderId == id).OrderByDescending(q => q.QuotedRate).FirstAsync();
            await CreateRepo(ctx).SubmitForApprovalAsync(id, chosen.Id, false, null);
            ctx.ChangeTracker.Clear();

            await CreateRepo(ctx).ApproveAsync(id, "Approved by MD");
            ctx.ChangeTracker.Clear();

            var header = await ctx.FreightRfqHeaders.FirstAsync(x => x.Id == id);
            header.StatusId.Should().Be(s.ApprovedId);
            header.ApprovedTransporterId.Should().Be(chosen.TransporterId);
            header.ApprovedRate.Should().Be(chosen.QuotedRate);
            header.ApprovedFreightValue.Should().Be(chosen.FreightValue);
        }

        [Fact]
        public async Task SoftDeleteAsync_Should_Set_IsDeleted()
        {
            await using var ctx = _fixture.CreateFreshDbContext();
            var s = await SeedMiscAsync(ctx);
            var id = await CreateRepo(ctx).CreateAsync(BuildHeader(s.PoBasedId), TransactionTypeId, CancellationToken.None);
            ctx.ChangeTracker.Clear();

            var result = await CreateRepo(ctx).SoftDeleteAsync(id, CancellationToken.None);
            ctx.ChangeTracker.Clear();

            result.Should().BeTrue();
            var deleted = await ctx.FreightRfqHeaders.IgnoreQueryFilters().FirstAsync(x => x.Id == id);
            deleted.IsDeleted.Should().Be(IsDelete.Deleted);
        }
    }
}
