// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QCManagement.Infrastructure.Data;

#nullable disable

namespace QCManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526115504_InitialQCMiscMasters")]
    partial class InitialQCMiscMasters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QCManagement.Domain.Entities.MiscMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Code");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MiscTypeId")
                        .HasColumnType("int")
                        .HasColumnName("MiscTypeId");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("SortOrder");

                    b.HasKey("Id");

                    b.HasIndex("MiscTypeId");

                    b.HasIndex("MiscTypeId", "Code")
                        .IsUnique();

                    b.ToTable("MiscMaster", "QC");
                });

            modelBuilder.Entity("QCManagement.Domain.Entities.MiscTypeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CreatedByName");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("CreatedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CreatedIP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("MiscTypeCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MiscTypeCode");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedBy");

                    b.Property<string>("ModifiedByName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ModifiedByName");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ModifiedIP");

                    b.HasKey("Id");

                    b.HasIndex("MiscTypeCode")
                        .IsUnique();

                    b.ToTable("MiscTypeMaster", "QC");
                });

            modelBuilder.Entity("QCManagement.Domain.Entities.MiscMaster", b =>
                {
                    b.HasOne("QCManagement.Domain.Entities.MiscTypeMaster", "MiscTypeMaster")
                        .WithMany("MiscMasters")
                        .HasForeignKey("MiscTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MiscTypeMaster");
                });

            modelBuilder.Entity("QCManagement.Domain.Entities.MiscTypeMaster", b =>
                {
                    b.Navigation("MiscMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
