namespace BackgroundService.QATests.Tests.ApprovalRequest;

// ─────────────────────────────────────────────────────────────────────────────
// ApprovalRequest — live-server QA suite (TRANSACTIONAL; no master CRUD).
//
// ApprovalRequest rows are NOT created via a master-data CRUD endpoint — they are
// produced by OTHER modules' workflows when a source transaction is wired to a
// workflow type. The controller therefore exposes only approve/upload/download and
// a set of read endpoints. The approve/upload happy paths are SKIPPED because they
// require a real pending ApprovalRequest generated upstream (no QA-clone seed).
//
// Contract verified against source (2026-06-18 — ApprovalRequestController.cs):
//   ⚠ Route prefix is "api/[controller]" → BASE = /api/ApprovalRequest (BARE, no module prefix).
//   POST /api/ApprovalRequest/approve              { items:[...] }  (ApproveApprovalRequestBatchCommand; perm CanApprove)
//   POST /api/ApprovalRequest/upload               (multipart IFormFile — UploadFileCommand)
//   GET  /api/ApprovalRequest/download?relativePath=
//   GET  /api/ApprovalRequest/approved-history?WorkflowType=&ModuleTransactionId=
//   GET  /api/ApprovalRequest/by-module?moduleTransactionId=&workflowTypeId=
//   GET  /api/ApprovalRequest/detail?moduleTransactionId=&workflowType=&pending=true
//
// Why approve/upload happy paths are SKIPPED:
//   They need a pending ApprovalRequest generated by a source transaction wired to a
//   workflow — the QA clone does not guarantee one. Attribute-level [Fact(Skip=...)] so
//   they are explicit pending work. Read reachability + no-auth + tolerant approve-empty
//   remain ACTIVE.
// ─────────────────────────────────────────────────────────────────────────────

[Collection("ApprovalRequestCollection")]
[TestCaseOrderer("Shared.QAInfrastructure.Infrastructure.PriorityOrderer", "Shared.QAInfrastructure")]
public sealed class ApprovalRequestQATests
{
    private readonly QAServerFixture _f;
    private const string BaseRoute = "/api/ApprovalRequest";

    public ApprovalRequestQATests(QAServerFixture fixture) => _f = fixture;

    // ─────────────────────────────────────────────────────────────────────────
    // SECTION 1 — APPROVE  (happy path BLOCKED; empty-body tolerant)
    // ─────────────────────────────────────────────────────────────────────────

    [Fact(Skip = "needs seeded data: a pending ApprovalRequest generated by a source transaction wired to a workflow"), TestPriority(1)]
    public async Task TC001_Approve_HappyPath_Returns200()
    {
        var resp = await _f.Client.PostAsJsonAsync($"{BaseRoute}/approve", new
        {
            items = new[]
            {
                new { approvalRequestId = 1, isApproved = true, remarks = "Approved by QA suite" }
            }
        });

        await QAHelper.AssertOkAsync(resp);
    }

    [Fact, TestPriority(2)]
    public async Task TC002_Approve_NoAuthToken_Returns401()
    {
        var resp = await _f.AnonymousClient.PostAsJsonAsync($"{BaseRoute}/approve", new
        {
            items = new[]
            {
                new { approvalRequestId = 1, isApproved = true }
            }
        });

        resp.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
    }

    [Fact, TestPriority(3)]
    public async Task TC003_Approve_EmptyBody_Returns200Or400()
    {
        // Batch command may accept an empty items envelope (→ 200 summary with zero counts)
        // or reject it (→ 400). Tolerate both.
        var resp = await _f.Client.PostAsJsonAsync($"{BaseRoute}/approve", new { });
        ((int)resp.StatusCode).Should().BeOneOf(200, 400);
    }

    [Fact, TestPriority(4)]
    public async Task TC004_Approve_EmptyItems_Returns200Or400()
    {
        var resp = await _f.Client.PostAsJsonAsync($"{BaseRoute}/approve", new { items = Array.Empty<object>() });
        ((int)resp.StatusCode).Should().BeOneOf(200, 400);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // SECTION 2 — UPLOAD  (multipart happy path BLOCKED)
    // ─────────────────────────────────────────────────────────────────────────

    [Fact(Skip = "needs seeded data: a multipart upload requires a real IFormFile bound to a pending ApprovalRequest workflow"), TestPriority(10)]
    public async Task TC010_Upload_HappyPath_Returns200()
    {
        // Placeholder — the upload endpoint binds a multipart IFormFile (UploadFileCommand);
        // exercising it needs a workflow-linked target which the clone does not seed.
        var resp = await _f.Client.PostAsJsonAsync($"{BaseRoute}/upload", new { });
        await QAHelper.AssertOkAsync(resp);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // SECTION 3 — DETAIL  (smoke reachability; tolerant 200/400/404)
    // ─────────────────────────────────────────────────────────────────────────

    [Fact, TestPriority(20)]
    [Trait("Layer", "Smoke")]
    public async Task TC020_GetDetail_Reachable_Returns200Or400Or404()
    {
        var resp = await _f.Client.GetAsync($"{BaseRoute}/detail?moduleTransactionId=1&workflowType=1&pending=true");
        ((int)resp.StatusCode).Should().BeOneOf(200, 400, 404);
    }

    [Fact, TestPriority(21)]
    public async Task TC021_GetDetail_NoAuthToken_Returns401()
    {
        var resp = await _f.AnonymousClient.GetAsync($"{BaseRoute}/detail?moduleTransactionId=1&workflowType=1&pending=true");
        resp.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // SECTION 4 — BY-MODULE + APPROVED-HISTORY  (reachability; tolerant 200/400/404)
    // ─────────────────────────────────────────────────────────────────────────

    [Fact, TestPriority(30)]
    public async Task TC030_GetByModule_Reachable_Returns200Or400Or404()
    {
        var resp = await _f.Client.GetAsync($"{BaseRoute}/by-module?moduleTransactionId=1&workflowTypeId=1");
        ((int)resp.StatusCode).Should().BeOneOf(200, 400, 404);
    }

    [Fact, TestPriority(31)]
    public async Task TC031_GetByModule_NoAuthToken_Returns401()
    {
        var resp = await _f.AnonymousClient.GetAsync($"{BaseRoute}/by-module?moduleTransactionId=1&workflowTypeId=1");
        resp.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
    }

    [Fact, TestPriority(32)]
    public async Task TC032_GetApprovedHistory_Reachable_Returns200Or400Or404()
    {
        var resp = await _f.Client.GetAsync($"{BaseRoute}/approved-history?WorkflowType=1&ModuleTransactionId=1");
        ((int)resp.StatusCode).Should().BeOneOf(200, 400, 404);
    }

    [Fact, TestPriority(33)]
    public async Task TC033_GetApprovedHistory_NoAuthToken_Returns401()
    {
        var resp = await _f.AnonymousClient.GetAsync($"{BaseRoute}/approved-history?WorkflowType=1&ModuleTransactionId=1");
        resp.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // SECTION 5 — DOWNLOAD  (nonexistent path; tolerant 400/404/500)
    // ─────────────────────────────────────────────────────────────────────────

    [Fact, TestPriority(40)]
    public async Task TC040_Download_NonExistentPath_Returns400Or404Or500()
    {
        // A nonexistent relativePath has no file to stream — backend may surface 400/404,
        // or throw (file-not-found) and bubble to 500. Tolerate all three.
        var resp = await _f.Client.GetAsync($"{BaseRoute}/download?relativePath=nonexistent/qa-missing-file.pdf");
        ((int)resp.StatusCode).Should().BeOneOf(400, 404, 500);
    }

    [Fact, TestPriority(41)]
    public async Task TC041_Download_NoAuthToken_Returns401()
    {
        var resp = await _f.AnonymousClient.GetAsync($"{BaseRoute}/download?relativePath=nonexistent/qa-missing-file.pdf");
        resp.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
    }
}
