global using Xunit;
global using FluentAssertions;
global using Moq;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Collections.Generic;
global using MediatR;
global using AutoMapper;
global using Contracts.Common;
global using Contracts.Dtos.Lookups.Production;
global using ProductionManagement.Domain.Events;
global using static ProductionManagement.Domain.Common.BaseEntity;
